# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtaildocs', '0007_merge'),
        ('projects', '0005_auto_20170424_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSchematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('company', models.CharField(blank=True, max_length=32, null=True)),
                ('schematic_url', models.URLField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='octopart_bom',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Schematic',
        ),
        migrations.DeleteModel(
            name='SchematicIndex',
        ),
        migrations.DeleteModel(
            name='SchematicTag',
        ),
        migrations.AddField(
            model_name='projectschematic',
            name='ramshackle_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schematics', to='projects.Project'),
        ),
    ]
