# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('projects', '0008_auto_20170509_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('company', models.CharField(blank=True, max_length=32, null=True)),
                ('schematic_url', models.URLField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectschematic',
            name='document',
        ),
        migrations.RemoveField(
            model_name='projectschematic',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projectschematic',
            name='ramshackle_project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='schematics',
        ),
        migrations.DeleteModel(
            name='ProjectSchematic',
        ),
    ]
