# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170509_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSchematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='schematics', to='projects.Project')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='schematic',
            name='name',
            field=models.CharField(default='Name', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectschematic',
            name='schematic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.Schematic'),
        ),
    ]
