# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselitem',
            name='centre_text',
            field=models.BooleanField(default=False),
        ),
    ]
